### ISSUE TITLE
Tracking of potential calibration problems

### ISSUE THREAD

**Issue by d-l-walker** [ACES-CMZ/reduction_ACES#178]
This issue is for tracking delivered data products that have been identified as having potential calibration issues. 

If you notice anything suspicious during weblog reviews, please make a note of this on the EB issue itself, and then reference it in this issue with a brief explanation of the problem(s).

Here's a summary of the EBs with identified problems thus far. Ultimately the impact in these cases it likely minor as the calibration looks OK in the end, but we may want to consider reprocessing at some point.

- #142: Tsys contamination that was not flagged (stage 7), phase jumps in bandpass scan on DA42 (WVR, stage 9), various outlying points in amp and phase plots (stage 17), absorption and phase spread for phase calibrator J1744 (stage 19). 
- #118: Absorption and phase spread for phase calibrator J1744 for a single MS. Other MSes were flagged appropriately (stage 19)

**Comment by xinglunju** [comment]
- #129 Phase spread for phase calibrator J1744 in a single scan for a single MS (stage 19). Likely due to antenna DA42 (stage 17).

**Comment by xinglunju** [comment]
- #241 Absorption for phase calibrator J1744, for the only MS in this SB (stage 19).

**Comment by xinglunju** [comment]
- #266 Absorption for phase calibrator J1744, for the two MSes in this SB (stage 19).

**Comment by keflavich** [comment]
This one too: https://github.com/ACES-CMZ/reduction_ACES/issues/272

**Comment by keflavich** [comment]
TODO: Send to ALMA & ask for QA3 to fix un-flagged absorption in SPW29 toward calibrator J1744.

**Comment by keflavich** [comment]
@snlongmore could you send this report to ALMA?

**Comment by keflavich** [comment]
@ashleythomasbarnes Go look for more of these.

**Comment by xinglunju** [comment]
7m data with HCO+ absorption, in SPW20: #6

**Comment by snlongmore** [comment]
I have just submitted a helpdesk ticket [21140](https://help.almascience.org/tickets/21140) and cc'd @ashleythomasbarnes  and @keflavich.

**Comment by xinglunju** [comment]
- #152 Phase spread for phase calibrator J1744 in a single scan for a single MS uid___A002_Xfda0c7_Xacb5.ms (stage 19).

**Comment by keflavich** [comment]
Todo:

* [ ] Check which were re-delivered @ashleythomasbarnes 
* [ ] Delete old tarballs
* [ ] Redownload
* [ ] Re-run scriptForPI
* [ ] Re-run imaging

**Comment by ashleythomasbarnes** [comment]
Confirm only Execution Block ID uid://A001/X15a0/Xbe Sgr_A_st_f_03_TM1 was initially re-processed.

**Comment by ashleythomasbarnes** [comment]
Phase spread in phase calibrator for the following (e.g. https://github.com/ACES-CMZ/reduction_ACES/issues/178#issuecomment-1451140404) is not an significant issue.

uid://A001/X15a0/X142 Sgr_A_st_ab_03_TM1
uid://A001/X15a0/X100 Sgr_A_st_q_03_TM1
uid://A001/X15a0/Xdc Sgr_A_st_k_03_TM1

I've been in touch with ALMA, and quoted response is the following.

> those deviations are within +/- 50 deg. If you flag those you will have only less data, no improvements in the result is expected. 

No further action needed.
